from . import encode as encode
from _typeshed import Incomplete

class Table:
    Bytes: Incomplete
    Pos: Incomplete
    def __init__(self, buf, pos) -> None: ...
    def Offset(self, vtableOffset): ...
    def Indirect(self, off): ...
    def String(self, off): ...
    def VectorLen(self, off): ...
    def Vector(self, off): ...
    def Union(self, t2, off) -> None: ...
    def Get(self, flags, off): ...
    def GetSlot(self, slot, d, validator_flags): ...
    def GetVectorAsNumpy(self, flags, off): ...
    def GetArrayAsNumpy(self, flags, off, length): ...
    def GetVOffsetTSlot(self, slot, d): ...
