from . import encode as encode, number_types as number_types, packer as packer

def GetSizePrefix(buf, offset): ...
def GetBufferIdentifier(buf, offset, size_prefixed: bool = False): ...
def BufferHasIdentifier(buf, offset, file_identifier, size_prefixed: bool = False): ...
def RemoveSizePrefix(buf, offset): ...
