# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Sample

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ChecklistItem(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ChecklistItem()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsChecklistItem(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ChecklistItem
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ChecklistItem
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ChecklistItem
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ChecklistItem
    def Description(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ChecklistItem
    def NextSessionGoal(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ChecklistItemStart(builder):
    builder.StartObject(4)

def Start(builder):
    ChecklistItemStart(builder)

def ChecklistItemAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    ChecklistItemAddId(builder, id)

def ChecklistItemAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    ChecklistItemAddName(builder, name)

def ChecklistItemAddDescription(builder, description):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(description), 0)

def AddDescription(builder, description):
    ChecklistItemAddDescription(builder, description)

def ChecklistItemAddNextSessionGoal(builder, nextSessionGoal):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(nextSessionGoal), 0)

def AddNextSessionGoal(builder, nextSessionGoal):
    ChecklistItemAddNextSessionGoal(builder, nextSessionGoal)

def ChecklistItemEnd(builder):
    return builder.EndObject()

def End(builder):
    return ChecklistItemEnd(builder)
