# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Sample

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GoalItem(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GoalItem()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGoalItem(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GoalItem
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GoalItem
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GoalItem
    def GoalDescription(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def GoalItemStart(builder):
    builder.StartObject(2)

def Start(builder):
    GoalItemStart(builder)

def GoalItemAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    GoalItemAddId(builder, id)

def GoalItemAddGoalDescription(builder, goalDescription):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(goalDescription), 0)

def AddGoalDescription(builder, goalDescription):
    GoalItemAddGoalDescription(builder, goalDescription)

def GoalItemEnd(builder):
    return builder.EndObject()

def End(builder):
    return GoalItemEnd(builder)
