# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Sample

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from MyGame.Sample.ChecklistItem import ChecklistItem
from MyGame.Sample.GoalItem import GoalItem
from typing import Optional
np = import_numpy()

class PhaseNode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PhaseNode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPhaseNode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PhaseNode
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PhaseNode
    def Id(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PhaseNode
    def Name(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PhaseNode
    def Goals(self, j: int) -> Optional[GoalItem]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = GoalItem()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PhaseNode
    def GoalsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PhaseNode
    def GoalsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # PhaseNode
    def Checklist(self, j: int) -> Optional[ChecklistItem]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = ChecklistItem()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PhaseNode
    def ChecklistLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PhaseNode
    def ChecklistIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def PhaseNodeStart(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    PhaseNodeStart(builder)

def PhaseNodeAddId(builder: flatbuffers.Builder, id: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder: flatbuffers.Builder, id: int):
    PhaseNodeAddId(builder, id)

def PhaseNodeAddName(builder: flatbuffers.Builder, name: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder: flatbuffers.Builder, name: int):
    PhaseNodeAddName(builder, name)

def PhaseNodeAddGoals(builder: flatbuffers.Builder, goals: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(goals), 0)

def AddGoals(builder: flatbuffers.Builder, goals: int):
    PhaseNodeAddGoals(builder, goals)

def PhaseNodeStartGoalsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartGoalsVector(builder, numElems: int) -> int:
    return PhaseNodeStartGoalsVector(builder, numElems)

def PhaseNodeAddChecklist(builder: flatbuffers.Builder, checklist: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(checklist), 0)

def AddChecklist(builder: flatbuffers.Builder, checklist: int):
    PhaseNodeAddChecklist(builder, checklist)

def PhaseNodeStartChecklistVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartChecklistVector(builder, numElems: int) -> int:
    return PhaseNodeStartChecklistVector(builder, numElems)

def PhaseNodeEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return PhaseNodeEnd(builder)
