# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Sample

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PhaseConnection(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PhaseConnection()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPhaseConnection(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PhaseConnection
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PhaseConnection
    def ConnectionId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PhaseConnection
    def PrevPhaseId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PhaseConnection
    def NextPhaseId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def PhaseConnectionStart(builder):
    builder.StartObject(3)

def Start(builder):
    PhaseConnectionStart(builder)

def PhaseConnectionAddConnectionId(builder, connectionId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(connectionId), 0)

def AddConnectionId(builder, connectionId):
    PhaseConnectionAddConnectionId(builder, connectionId)

def PhaseConnectionAddPrevPhaseId(builder, prevPhaseId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(prevPhaseId), 0)

def AddPrevPhaseId(builder, prevPhaseId):
    PhaseConnectionAddPrevPhaseId(builder, prevPhaseId)

def PhaseConnectionAddNextPhaseId(builder, nextPhaseId):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(nextPhaseId), 0)

def AddNextPhaseId(builder, nextPhaseId):
    PhaseConnectionAddNextPhaseId(builder, nextPhaseId)

def PhaseConnectionEnd(builder):
    return builder.EndObject()

def End(builder):
    return PhaseConnectionEnd(builder)
