# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Sample

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UserModel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UserModel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUserModel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UserModel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UserModel
    def CurrentUserPhase(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UserModel
    def CurrentUserChecklist(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MyGame.Sample.ChecklistItem import ChecklistItem
            obj = ChecklistItem()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # UserModel
    def CurrentUserChecklistLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # UserModel
    def CurrentUserChecklistIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # UserModel
    def LastSessionSummary(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UserModel
    def ClientProfileAssessment(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UserModel
    def NextSessionGoals(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UserModel
    def LastObserverAccessTimestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # UserModel
    def LastRemovedChecklistItems(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # UserModel
    def LastRemovedChecklistItemsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # UserModel
    def LastRemovedChecklistItemsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # UserModel
    def GoalReviewCheck(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UserModel
    def Memories(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MyGame.Sample.MemoryModel import MemoryModel
            obj = MemoryModel()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # UserModel
    def ConversationTranscript(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MyGame.Sample.ConversationTranscript import ConversationTranscript
            obj = ConversationTranscript()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # UserModel
    def SentimentAnalysis(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MyGame.Sample.SentimentAnalysis import SentimentAnalysis
            obj = SentimentAnalysis()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def UserModelStart(builder):
    builder.StartObject(11)

def Start(builder):
    UserModelStart(builder)

def UserModelAddCurrentUserPhase(builder, currentUserPhase):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(currentUserPhase), 0)

def AddCurrentUserPhase(builder, currentUserPhase):
    UserModelAddCurrentUserPhase(builder, currentUserPhase)

def UserModelAddCurrentUserChecklist(builder, currentUserChecklist):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(currentUserChecklist), 0)

def AddCurrentUserChecklist(builder, currentUserChecklist):
    UserModelAddCurrentUserChecklist(builder, currentUserChecklist)

def UserModelStartCurrentUserChecklistVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartCurrentUserChecklistVector(builder, numElems: int) -> int:
    return UserModelStartCurrentUserChecklistVector(builder, numElems)

def UserModelAddLastSessionSummary(builder, lastSessionSummary):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(lastSessionSummary), 0)

def AddLastSessionSummary(builder, lastSessionSummary):
    UserModelAddLastSessionSummary(builder, lastSessionSummary)

def UserModelAddClientProfileAssessment(builder, clientProfileAssessment):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(clientProfileAssessment), 0)

def AddClientProfileAssessment(builder, clientProfileAssessment):
    UserModelAddClientProfileAssessment(builder, clientProfileAssessment)

def UserModelAddNextSessionGoals(builder, nextSessionGoals):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(nextSessionGoals), 0)

def AddNextSessionGoals(builder, nextSessionGoals):
    UserModelAddNextSessionGoals(builder, nextSessionGoals)

def UserModelAddLastObserverAccessTimestamp(builder, lastObserverAccessTimestamp):
    builder.PrependInt64Slot(5, lastObserverAccessTimestamp, 0)

def AddLastObserverAccessTimestamp(builder, lastObserverAccessTimestamp):
    UserModelAddLastObserverAccessTimestamp(builder, lastObserverAccessTimestamp)

def UserModelAddLastRemovedChecklistItems(builder, lastRemovedChecklistItems):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(lastRemovedChecklistItems), 0)

def AddLastRemovedChecklistItems(builder, lastRemovedChecklistItems):
    UserModelAddLastRemovedChecklistItems(builder, lastRemovedChecklistItems)

def UserModelStartLastRemovedChecklistItemsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartLastRemovedChecklistItemsVector(builder, numElems: int) -> int:
    return UserModelStartLastRemovedChecklistItemsVector(builder, numElems)

def UserModelAddGoalReviewCheck(builder, goalReviewCheck):
    builder.PrependBoolSlot(7, goalReviewCheck, 0)

def AddGoalReviewCheck(builder, goalReviewCheck):
    UserModelAddGoalReviewCheck(builder, goalReviewCheck)

def UserModelAddMemories(builder, memories):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(memories), 0)

def AddMemories(builder, memories):
    UserModelAddMemories(builder, memories)

def UserModelAddConversationTranscript(builder, conversationTranscript):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(conversationTranscript), 0)

def AddConversationTranscript(builder, conversationTranscript):
    UserModelAddConversationTranscript(builder, conversationTranscript)

def UserModelAddSentimentAnalysis(builder, sentimentAnalysis):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(sentimentAnalysis), 0)

def AddSentimentAnalysis(builder, sentimentAnalysis):
    UserModelAddSentimentAnalysis(builder, sentimentAnalysis)

def UserModelEnd(builder):
    return builder.EndObject()

def End(builder):
    return UserModelEnd(builder)
