# automatically generated by the FlatBuffers compiler, do not modify

# namespace: sco3fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Hello(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Hello()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHello(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Hello
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Hello
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Hello
    def Size(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def HelloStart(builder):
    builder.StartObject(2)

def Start(builder):
    HelloStart(builder)

def HelloAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    HelloAddName(builder, name)

def HelloAddSize(builder, size):
    builder.PrependUint32Slot(1, size, 0)

def AddSize(builder, size):
    HelloAddSize(builder, size)

def HelloEnd(builder):
    return builder.EndObject()

def End(builder):
    return HelloEnd(builder)
