// source: api.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var google_protobuf_any_pb = require('google-protobuf/google/protobuf/any_pb.js');
goog.object.extend(proto, google_protobuf_any_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.ChecklistItem', null, global);
goog.exportSymbol('proto.ComponentType', null, global);
goog.exportSymbol('proto.ConversationItem', null, global);
goog.exportSymbol('proto.ConversationStreamMessage', null, global);
goog.exportSymbol('proto.ConversationTranscript', null, global);
goog.exportSymbol('proto.GoalItem', null, global);
goog.exportSymbol('proto.MemoryField', null, global);
goog.exportSymbol('proto.MemoryModel', null, global);
goog.exportSymbol('proto.PhaseConnection', null, global);
goog.exportSymbol('proto.PhaseInformation', null, global);
goog.exportSymbol('proto.PhaseNode', null, global);
goog.exportSymbol('proto.SentimentAnalysis', null, global);
goog.exportSymbol('proto.UserModel', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SentimentAnalysis = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SentimentAnalysis, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SentimentAnalysis.displayName = 'proto.SentimentAnalysis';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ConversationItem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ConversationItem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ConversationItem.displayName = 'proto.ConversationItem';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ConversationTranscript = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ConversationTranscript.repeatedFields_, null);
};
goog.inherits(proto.ConversationTranscript, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ConversationTranscript.displayName = 'proto.ConversationTranscript';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ChecklistItem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ChecklistItem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ChecklistItem.displayName = 'proto.ChecklistItem';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GoalItem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.GoalItem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.GoalItem.displayName = 'proto.GoalItem';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PhaseNode = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.PhaseNode.repeatedFields_, null);
};
goog.inherits(proto.PhaseNode, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PhaseNode.displayName = 'proto.PhaseNode';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PhaseConnection = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.PhaseConnection, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PhaseConnection.displayName = 'proto.PhaseConnection';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PhaseInformation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.PhaseInformation.repeatedFields_, null);
};
goog.inherits(proto.PhaseInformation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PhaseInformation.displayName = 'proto.PhaseInformation';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MemoryField = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.MemoryField.repeatedFields_, null);
};
goog.inherits(proto.MemoryField, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.MemoryField.displayName = 'proto.MemoryField';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MemoryModel = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.MemoryModel.repeatedFields_, null);
};
goog.inherits(proto.MemoryModel, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.MemoryModel.displayName = 'proto.MemoryModel';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.UserModel = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.UserModel.repeatedFields_, null);
};
goog.inherits(proto.UserModel, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.UserModel.displayName = 'proto.UserModel';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ConversationStreamMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ConversationStreamMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ConversationStreamMessage.displayName = 'proto.ConversationStreamMessage';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SentimentAnalysis.prototype.toObject = function(opt_includeInstance) {
  return proto.SentimentAnalysis.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SentimentAnalysis} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SentimentAnalysis.toObject = function(includeInstance, msg) {
  var f, obj = {
    currentSentiment: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    trendingSentiment: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    totalSentiment: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    messageCount: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    averageSentiment: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SentimentAnalysis}
 */
proto.SentimentAnalysis.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SentimentAnalysis;
  return proto.SentimentAnalysis.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SentimentAnalysis} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SentimentAnalysis}
 */
proto.SentimentAnalysis.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setCurrentSentiment(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTrendingSentiment(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTotalSentiment(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setMessageCount(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setAverageSentiment(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SentimentAnalysis.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SentimentAnalysis.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SentimentAnalysis} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SentimentAnalysis.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCurrentSentiment();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getTrendingSentiment();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getTotalSentiment();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getMessageCount();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getAverageSentiment();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
};


/**
 * optional double current_sentiment = 1;
 * @return {number}
 */
proto.SentimentAnalysis.prototype.getCurrentSentiment = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.SentimentAnalysis} returns this
 */
proto.SentimentAnalysis.prototype.setCurrentSentiment = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional double trending_sentiment = 2;
 * @return {number}
 */
proto.SentimentAnalysis.prototype.getTrendingSentiment = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.SentimentAnalysis} returns this
 */
proto.SentimentAnalysis.prototype.setTrendingSentiment = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional double total_sentiment = 3;
 * @return {number}
 */
proto.SentimentAnalysis.prototype.getTotalSentiment = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.SentimentAnalysis} returns this
 */
proto.SentimentAnalysis.prototype.setTotalSentiment = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional double message_count = 4;
 * @return {number}
 */
proto.SentimentAnalysis.prototype.getMessageCount = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.SentimentAnalysis} returns this
 */
proto.SentimentAnalysis.prototype.setMessageCount = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional double average_sentiment = 5;
 * @return {number}
 */
proto.SentimentAnalysis.prototype.getAverageSentiment = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.SentimentAnalysis} returns this
 */
proto.SentimentAnalysis.prototype.setAverageSentiment = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ConversationItem.prototype.toObject = function(opt_includeInstance) {
  return proto.ConversationItem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ConversationItem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ConversationItem.toObject = function(includeInstance, msg) {
  var f, obj = {
    role: jspb.Message.getFieldWithDefault(msg, 1, ""),
    content: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ConversationItem}
 */
proto.ConversationItem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ConversationItem;
  return proto.ConversationItem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ConversationItem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ConversationItem}
 */
proto.ConversationItem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRole(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setContent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ConversationItem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ConversationItem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ConversationItem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ConversationItem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRole();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getContent();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string role = 1;
 * @return {string}
 */
proto.ConversationItem.prototype.getRole = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ConversationItem} returns this
 */
proto.ConversationItem.prototype.setRole = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string content = 2;
 * @return {string}
 */
proto.ConversationItem.prototype.getContent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ConversationItem} returns this
 */
proto.ConversationItem.prototype.setContent = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ConversationTranscript.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ConversationTranscript.prototype.toObject = function(opt_includeInstance) {
  return proto.ConversationTranscript.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ConversationTranscript} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ConversationTranscript.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    conversationList: jspb.Message.toObjectList(msg.getConversationList(),
    proto.ConversationItem.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ConversationTranscript}
 */
proto.ConversationTranscript.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ConversationTranscript;
  return proto.ConversationTranscript.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ConversationTranscript} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ConversationTranscript}
 */
proto.ConversationTranscript.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = new proto.ConversationItem;
      reader.readMessage(value,proto.ConversationItem.deserializeBinaryFromReader);
      msg.addConversation(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ConversationTranscript.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ConversationTranscript.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ConversationTranscript} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ConversationTranscript.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getConversationList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.ConversationItem.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.ConversationTranscript.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ConversationTranscript} returns this
 */
proto.ConversationTranscript.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated ConversationItem conversation = 2;
 * @return {!Array<!proto.ConversationItem>}
 */
proto.ConversationTranscript.prototype.getConversationList = function() {
  return /** @type{!Array<!proto.ConversationItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ConversationItem, 2));
};


/**
 * @param {!Array<!proto.ConversationItem>} value
 * @return {!proto.ConversationTranscript} returns this
*/
proto.ConversationTranscript.prototype.setConversationList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.ConversationItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ConversationItem}
 */
proto.ConversationTranscript.prototype.addConversation = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.ConversationItem, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ConversationTranscript} returns this
 */
proto.ConversationTranscript.prototype.clearConversationList = function() {
  return this.setConversationList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ChecklistItem.prototype.toObject = function(opt_includeInstance) {
  return proto.ChecklistItem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ChecklistItem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ChecklistItem.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    description: jspb.Message.getFieldWithDefault(msg, 3, ""),
    nextSessionGoal: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ChecklistItem}
 */
proto.ChecklistItem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ChecklistItem;
  return proto.ChecklistItem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ChecklistItem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ChecklistItem}
 */
proto.ChecklistItem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setNextSessionGoal(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ChecklistItem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ChecklistItem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ChecklistItem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ChecklistItem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getNextSessionGoal();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.ChecklistItem.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ChecklistItem} returns this
 */
proto.ChecklistItem.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.ChecklistItem.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ChecklistItem} returns this
 */
proto.ChecklistItem.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string description = 3;
 * @return {string}
 */
proto.ChecklistItem.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.ChecklistItem} returns this
 */
proto.ChecklistItem.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string next_session_goal = 4;
 * @return {string}
 */
proto.ChecklistItem.prototype.getNextSessionGoal = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.ChecklistItem} returns this
 */
proto.ChecklistItem.prototype.setNextSessionGoal = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GoalItem.prototype.toObject = function(opt_includeInstance) {
  return proto.GoalItem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GoalItem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GoalItem.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    goalDescription: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GoalItem}
 */
proto.GoalItem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GoalItem;
  return proto.GoalItem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GoalItem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GoalItem}
 */
proto.GoalItem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setGoalDescription(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GoalItem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GoalItem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GoalItem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GoalItem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getGoalDescription();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.GoalItem.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.GoalItem} returns this
 */
proto.GoalItem.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string goal_description = 2;
 * @return {string}
 */
proto.GoalItem.prototype.getGoalDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.GoalItem} returns this
 */
proto.GoalItem.prototype.setGoalDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.PhaseNode.repeatedFields_ = [3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PhaseNode.prototype.toObject = function(opt_includeInstance) {
  return proto.PhaseNode.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PhaseNode} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PhaseNode.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    goalsList: jspb.Message.toObjectList(msg.getGoalsList(),
    proto.GoalItem.toObject, includeInstance),
    checklistList: jspb.Message.toObjectList(msg.getChecklistList(),
    proto.ChecklistItem.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PhaseNode}
 */
proto.PhaseNode.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PhaseNode;
  return proto.PhaseNode.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PhaseNode} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PhaseNode}
 */
proto.PhaseNode.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = new proto.GoalItem;
      reader.readMessage(value,proto.GoalItem.deserializeBinaryFromReader);
      msg.addGoals(value);
      break;
    case 4:
      var value = new proto.ChecklistItem;
      reader.readMessage(value,proto.ChecklistItem.deserializeBinaryFromReader);
      msg.addChecklist(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PhaseNode.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PhaseNode.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PhaseNode} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PhaseNode.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getGoalsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.GoalItem.serializeBinaryToWriter
    );
  }
  f = message.getChecklistList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.ChecklistItem.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.PhaseNode.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.PhaseNode} returns this
 */
proto.PhaseNode.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.PhaseNode.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.PhaseNode} returns this
 */
proto.PhaseNode.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated GoalItem goals = 3;
 * @return {!Array<!proto.GoalItem>}
 */
proto.PhaseNode.prototype.getGoalsList = function() {
  return /** @type{!Array<!proto.GoalItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.GoalItem, 3));
};


/**
 * @param {!Array<!proto.GoalItem>} value
 * @return {!proto.PhaseNode} returns this
*/
proto.PhaseNode.prototype.setGoalsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.GoalItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.GoalItem}
 */
proto.PhaseNode.prototype.addGoals = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.GoalItem, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.PhaseNode} returns this
 */
proto.PhaseNode.prototype.clearGoalsList = function() {
  return this.setGoalsList([]);
};


/**
 * repeated ChecklistItem checklist = 4;
 * @return {!Array<!proto.ChecklistItem>}
 */
proto.PhaseNode.prototype.getChecklistList = function() {
  return /** @type{!Array<!proto.ChecklistItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ChecklistItem, 4));
};


/**
 * @param {!Array<!proto.ChecklistItem>} value
 * @return {!proto.PhaseNode} returns this
*/
proto.PhaseNode.prototype.setChecklistList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.ChecklistItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ChecklistItem}
 */
proto.PhaseNode.prototype.addChecklist = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.ChecklistItem, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.PhaseNode} returns this
 */
proto.PhaseNode.prototype.clearChecklistList = function() {
  return this.setChecklistList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PhaseConnection.prototype.toObject = function(opt_includeInstance) {
  return proto.PhaseConnection.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PhaseConnection} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PhaseConnection.toObject = function(includeInstance, msg) {
  var f, obj = {
    connectionId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    prevPhaseId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    nextPhaseId: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PhaseConnection}
 */
proto.PhaseConnection.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PhaseConnection;
  return proto.PhaseConnection.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PhaseConnection} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PhaseConnection}
 */
proto.PhaseConnection.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setConnectionId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPrevPhaseId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setNextPhaseId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PhaseConnection.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PhaseConnection.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PhaseConnection} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PhaseConnection.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getConnectionId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPrevPhaseId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getNextPhaseId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string connection_id = 1;
 * @return {string}
 */
proto.PhaseConnection.prototype.getConnectionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.PhaseConnection} returns this
 */
proto.PhaseConnection.prototype.setConnectionId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string prev_phase_id = 2;
 * @return {string}
 */
proto.PhaseConnection.prototype.getPrevPhaseId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.PhaseConnection} returns this
 */
proto.PhaseConnection.prototype.setPrevPhaseId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string next_phase_id = 3;
 * @return {string}
 */
proto.PhaseConnection.prototype.getNextPhaseId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.PhaseConnection} returns this
 */
proto.PhaseConnection.prototype.setNextPhaseId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.PhaseInformation.repeatedFields_ = [2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PhaseInformation.prototype.toObject = function(opt_includeInstance) {
  return proto.PhaseInformation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PhaseInformation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PhaseInformation.toObject = function(includeInstance, msg) {
  var f, obj = {
    startPhaseId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    phaseNodesList: jspb.Message.toObjectList(msg.getPhaseNodesList(),
    proto.PhaseNode.toObject, includeInstance),
    phaseConnectionsList: jspb.Message.toObjectList(msg.getPhaseConnectionsList(),
    proto.PhaseConnection.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PhaseInformation}
 */
proto.PhaseInformation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PhaseInformation;
  return proto.PhaseInformation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PhaseInformation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PhaseInformation}
 */
proto.PhaseInformation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setStartPhaseId(value);
      break;
    case 2:
      var value = new proto.PhaseNode;
      reader.readMessage(value,proto.PhaseNode.deserializeBinaryFromReader);
      msg.addPhaseNodes(value);
      break;
    case 3:
      var value = new proto.PhaseConnection;
      reader.readMessage(value,proto.PhaseConnection.deserializeBinaryFromReader);
      msg.addPhaseConnections(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PhaseInformation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PhaseInformation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PhaseInformation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PhaseInformation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStartPhaseId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPhaseNodesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.PhaseNode.serializeBinaryToWriter
    );
  }
  f = message.getPhaseConnectionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.PhaseConnection.serializeBinaryToWriter
    );
  }
};


/**
 * optional string start_phase_id = 1;
 * @return {string}
 */
proto.PhaseInformation.prototype.getStartPhaseId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.PhaseInformation} returns this
 */
proto.PhaseInformation.prototype.setStartPhaseId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated PhaseNode phase_nodes = 2;
 * @return {!Array<!proto.PhaseNode>}
 */
proto.PhaseInformation.prototype.getPhaseNodesList = function() {
  return /** @type{!Array<!proto.PhaseNode>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.PhaseNode, 2));
};


/**
 * @param {!Array<!proto.PhaseNode>} value
 * @return {!proto.PhaseInformation} returns this
*/
proto.PhaseInformation.prototype.setPhaseNodesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.PhaseNode=} opt_value
 * @param {number=} opt_index
 * @return {!proto.PhaseNode}
 */
proto.PhaseInformation.prototype.addPhaseNodes = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.PhaseNode, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.PhaseInformation} returns this
 */
proto.PhaseInformation.prototype.clearPhaseNodesList = function() {
  return this.setPhaseNodesList([]);
};


/**
 * repeated PhaseConnection phase_connections = 3;
 * @return {!Array<!proto.PhaseConnection>}
 */
proto.PhaseInformation.prototype.getPhaseConnectionsList = function() {
  return /** @type{!Array<!proto.PhaseConnection>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.PhaseConnection, 3));
};


/**
 * @param {!Array<!proto.PhaseConnection>} value
 * @return {!proto.PhaseInformation} returns this
*/
proto.PhaseInformation.prototype.setPhaseConnectionsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.PhaseConnection=} opt_value
 * @param {number=} opt_index
 * @return {!proto.PhaseConnection}
 */
proto.PhaseInformation.prototype.addPhaseConnections = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.PhaseConnection, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.PhaseInformation} returns this
 */
proto.PhaseInformation.prototype.clearPhaseConnectionsList = function() {
  return this.setPhaseConnectionsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.MemoryField.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MemoryField.prototype.toObject = function(opt_includeInstance) {
  return proto.MemoryField.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MemoryField} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MemoryField.toObject = function(includeInstance, msg) {
  var f, obj = {
    fieldName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    description: jspb.Message.getFieldWithDefault(msg, 2, ""),
    content: jspb.Message.getFieldWithDefault(msg, 3, ""),
    contextWordsList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MemoryField}
 */
proto.MemoryField.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MemoryField;
  return proto.MemoryField.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MemoryField} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MemoryField}
 */
proto.MemoryField.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFieldName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setContent(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.addContextWords(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MemoryField.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MemoryField.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MemoryField} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MemoryField.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFieldName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getContent();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getContextWordsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      4,
      f
    );
  }
};


/**
 * optional string field_name = 1;
 * @return {string}
 */
proto.MemoryField.prototype.getFieldName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.MemoryField} returns this
 */
proto.MemoryField.prototype.setFieldName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string description = 2;
 * @return {string}
 */
proto.MemoryField.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.MemoryField} returns this
 */
proto.MemoryField.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string content = 3;
 * @return {string}
 */
proto.MemoryField.prototype.getContent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.MemoryField} returns this
 */
proto.MemoryField.prototype.setContent = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * repeated string context_words = 4;
 * @return {!Array<string>}
 */
proto.MemoryField.prototype.getContextWordsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.MemoryField} returns this
 */
proto.MemoryField.prototype.setContextWordsList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.MemoryField} returns this
 */
proto.MemoryField.prototype.addContextWords = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.MemoryField} returns this
 */
proto.MemoryField.prototype.clearContextWordsList = function() {
  return this.setContextWordsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.MemoryModel.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MemoryModel.prototype.toObject = function(opt_includeInstance) {
  return proto.MemoryModel.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MemoryModel} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MemoryModel.toObject = function(includeInstance, msg) {
  var f, obj = {
    memoryFieldsList: jspb.Message.toObjectList(msg.getMemoryFieldsList(),
    proto.MemoryField.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MemoryModel}
 */
proto.MemoryModel.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MemoryModel;
  return proto.MemoryModel.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MemoryModel} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MemoryModel}
 */
proto.MemoryModel.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.MemoryField;
      reader.readMessage(value,proto.MemoryField.deserializeBinaryFromReader);
      msg.addMemoryFields(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MemoryModel.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MemoryModel.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MemoryModel} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MemoryModel.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMemoryFieldsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.MemoryField.serializeBinaryToWriter
    );
  }
};


/**
 * repeated MemoryField memory_fields = 1;
 * @return {!Array<!proto.MemoryField>}
 */
proto.MemoryModel.prototype.getMemoryFieldsList = function() {
  return /** @type{!Array<!proto.MemoryField>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.MemoryField, 1));
};


/**
 * @param {!Array<!proto.MemoryField>} value
 * @return {!proto.MemoryModel} returns this
*/
proto.MemoryModel.prototype.setMemoryFieldsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.MemoryField=} opt_value
 * @param {number=} opt_index
 * @return {!proto.MemoryField}
 */
proto.MemoryModel.prototype.addMemoryFields = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.MemoryField, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.MemoryModel} returns this
 */
proto.MemoryModel.prototype.clearMemoryFieldsList = function() {
  return this.setMemoryFieldsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.UserModel.repeatedFields_ = [2,7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.UserModel.prototype.toObject = function(opt_includeInstance) {
  return proto.UserModel.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.UserModel} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.UserModel.toObject = function(includeInstance, msg) {
  var f, obj = {
    currentUserPhase: jspb.Message.getFieldWithDefault(msg, 1, ""),
    currentUserChecklistList: jspb.Message.toObjectList(msg.getCurrentUserChecklistList(),
    proto.ChecklistItem.toObject, includeInstance),
    lastSessionSummary: jspb.Message.getFieldWithDefault(msg, 3, ""),
    clientProfileAssessment: jspb.Message.getFieldWithDefault(msg, 4, ""),
    nextSessionGoals: jspb.Message.getFieldWithDefault(msg, 5, ""),
    lastObserverAccessTimestamp: jspb.Message.getFieldWithDefault(msg, 6, 0),
    lastRemovedChecklistItemsList: (f = jspb.Message.getRepeatedField(msg, 7)) == null ? undefined : f,
    goalReviewCheck: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
    memories: (f = msg.getMemories()) && proto.MemoryModel.toObject(includeInstance, f),
    conversationTranscript: (f = msg.getConversationTranscript()) && proto.ConversationTranscript.toObject(includeInstance, f),
    sentimentAnalysis: (f = msg.getSentimentAnalysis()) && proto.SentimentAnalysis.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.UserModel}
 */
proto.UserModel.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.UserModel;
  return proto.UserModel.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.UserModel} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.UserModel}
 */
proto.UserModel.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCurrentUserPhase(value);
      break;
    case 2:
      var value = new proto.ChecklistItem;
      reader.readMessage(value,proto.ChecklistItem.deserializeBinaryFromReader);
      msg.addCurrentUserChecklist(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setLastSessionSummary(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setClientProfileAssessment(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setNextSessionGoals(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLastObserverAccessTimestamp(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.addLastRemovedChecklistItems(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setGoalReviewCheck(value);
      break;
    case 9:
      var value = new proto.MemoryModel;
      reader.readMessage(value,proto.MemoryModel.deserializeBinaryFromReader);
      msg.setMemories(value);
      break;
    case 10:
      var value = new proto.ConversationTranscript;
      reader.readMessage(value,proto.ConversationTranscript.deserializeBinaryFromReader);
      msg.setConversationTranscript(value);
      break;
    case 11:
      var value = new proto.SentimentAnalysis;
      reader.readMessage(value,proto.SentimentAnalysis.deserializeBinaryFromReader);
      msg.setSentimentAnalysis(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.UserModel.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.UserModel.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.UserModel} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.UserModel.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCurrentUserPhase();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCurrentUserChecklistList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.ChecklistItem.serializeBinaryToWriter
    );
  }
  f = message.getLastSessionSummary();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getClientProfileAssessment();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getNextSessionGoals();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getLastObserverAccessTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
  f = message.getLastRemovedChecklistItemsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      7,
      f
    );
  }
  f = message.getGoalReviewCheck();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getMemories();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.MemoryModel.serializeBinaryToWriter
    );
  }
  f = message.getConversationTranscript();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.ConversationTranscript.serializeBinaryToWriter
    );
  }
  f = message.getSentimentAnalysis();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      proto.SentimentAnalysis.serializeBinaryToWriter
    );
  }
};


/**
 * optional string current_user_phase = 1;
 * @return {string}
 */
proto.UserModel.prototype.getCurrentUserPhase = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.UserModel} returns this
 */
proto.UserModel.prototype.setCurrentUserPhase = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated ChecklistItem current_user_checklist = 2;
 * @return {!Array<!proto.ChecklistItem>}
 */
proto.UserModel.prototype.getCurrentUserChecklistList = function() {
  return /** @type{!Array<!proto.ChecklistItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ChecklistItem, 2));
};


/**
 * @param {!Array<!proto.ChecklistItem>} value
 * @return {!proto.UserModel} returns this
*/
proto.UserModel.prototype.setCurrentUserChecklistList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.ChecklistItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ChecklistItem}
 */
proto.UserModel.prototype.addCurrentUserChecklist = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.ChecklistItem, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.UserModel} returns this
 */
proto.UserModel.prototype.clearCurrentUserChecklistList = function() {
  return this.setCurrentUserChecklistList([]);
};


/**
 * optional string last_session_summary = 3;
 * @return {string}
 */
proto.UserModel.prototype.getLastSessionSummary = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.UserModel} returns this
 */
proto.UserModel.prototype.setLastSessionSummary = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string client_profile_assessment = 4;
 * @return {string}
 */
proto.UserModel.prototype.getClientProfileAssessment = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.UserModel} returns this
 */
proto.UserModel.prototype.setClientProfileAssessment = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string next_session_goals = 5;
 * @return {string}
 */
proto.UserModel.prototype.getNextSessionGoals = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.UserModel} returns this
 */
proto.UserModel.prototype.setNextSessionGoals = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional int64 last_observer_access_timestamp = 6;
 * @return {number}
 */
proto.UserModel.prototype.getLastObserverAccessTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.UserModel} returns this
 */
proto.UserModel.prototype.setLastObserverAccessTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * repeated string last_removed_checklist_items = 7;
 * @return {!Array<string>}
 */
proto.UserModel.prototype.getLastRemovedChecklistItemsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 7));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.UserModel} returns this
 */
proto.UserModel.prototype.setLastRemovedChecklistItemsList = function(value) {
  return jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.UserModel} returns this
 */
proto.UserModel.prototype.addLastRemovedChecklistItems = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.UserModel} returns this
 */
proto.UserModel.prototype.clearLastRemovedChecklistItemsList = function() {
  return this.setLastRemovedChecklistItemsList([]);
};


/**
 * optional bool goal_review_check = 8;
 * @return {boolean}
 */
proto.UserModel.prototype.getGoalReviewCheck = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.UserModel} returns this
 */
proto.UserModel.prototype.setGoalReviewCheck = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * optional MemoryModel memories = 9;
 * @return {?proto.MemoryModel}
 */
proto.UserModel.prototype.getMemories = function() {
  return /** @type{?proto.MemoryModel} */ (
    jspb.Message.getWrapperField(this, proto.MemoryModel, 9));
};


/**
 * @param {?proto.MemoryModel|undefined} value
 * @return {!proto.UserModel} returns this
*/
proto.UserModel.prototype.setMemories = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.UserModel} returns this
 */
proto.UserModel.prototype.clearMemories = function() {
  return this.setMemories(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.UserModel.prototype.hasMemories = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional ConversationTranscript conversation_transcript = 10;
 * @return {?proto.ConversationTranscript}
 */
proto.UserModel.prototype.getConversationTranscript = function() {
  return /** @type{?proto.ConversationTranscript} */ (
    jspb.Message.getWrapperField(this, proto.ConversationTranscript, 10));
};


/**
 * @param {?proto.ConversationTranscript|undefined} value
 * @return {!proto.UserModel} returns this
*/
proto.UserModel.prototype.setConversationTranscript = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.UserModel} returns this
 */
proto.UserModel.prototype.clearConversationTranscript = function() {
  return this.setConversationTranscript(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.UserModel.prototype.hasConversationTranscript = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional SentimentAnalysis sentiment_analysis = 11;
 * @return {?proto.SentimentAnalysis}
 */
proto.UserModel.prototype.getSentimentAnalysis = function() {
  return /** @type{?proto.SentimentAnalysis} */ (
    jspb.Message.getWrapperField(this, proto.SentimentAnalysis, 11));
};


/**
 * @param {?proto.SentimentAnalysis|undefined} value
 * @return {!proto.UserModel} returns this
*/
proto.UserModel.prototype.setSentimentAnalysis = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.UserModel} returns this
 */
proto.UserModel.prototype.clearSentimentAnalysis = function() {
  return this.setSentimentAnalysis(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.UserModel.prototype.hasSentimentAnalysis = function() {
  return jspb.Message.getField(this, 11) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ConversationStreamMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.ConversationStreamMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ConversationStreamMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ConversationStreamMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    sequenceNumber: jspb.Message.getFieldWithDefault(msg, 1, 0),
    content: (f = msg.getContent()) && google_protobuf_any_pb.Any.toObject(includeInstance, f),
    dateTime: jspb.Message.getFieldWithDefault(msg, 3, ""),
    sessionId: jspb.Message.getFieldWithDefault(msg, 4, ""),
    subscriberId: jspb.Message.getFieldWithDefault(msg, 5, ""),
    applicationName: jspb.Message.getFieldWithDefault(msg, 6, ""),
    messageType: jspb.Message.getFieldWithDefault(msg, 7, 0),
    source: jspb.Message.getFieldWithDefault(msg, 8, ""),
    destination: jspb.Message.getFieldWithDefault(msg, 9, ""),
    docSource: jspb.Message.getFieldWithDefault(msg, 10, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ConversationStreamMessage}
 */
proto.ConversationStreamMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ConversationStreamMessage;
  return proto.ConversationStreamMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ConversationStreamMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ConversationStreamMessage}
 */
proto.ConversationStreamMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSequenceNumber(value);
      break;
    case 2:
      var value = new google_protobuf_any_pb.Any;
      reader.readMessage(value,google_protobuf_any_pb.Any.deserializeBinaryFromReader);
      msg.setContent(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDateTime(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setSessionId(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubscriberId(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setApplicationName(value);
      break;
    case 7:
      var value = /** @type {!proto.ComponentType} */ (reader.readEnum());
      msg.setMessageType(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setSource(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setDestination(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setDocSource(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ConversationStreamMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ConversationStreamMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ConversationStreamMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ConversationStreamMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSequenceNumber();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getContent();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_any_pb.Any.serializeBinaryToWriter
    );
  }
  f = message.getDateTime();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getSessionId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getSubscriberId();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getApplicationName();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getMessageType();
  if (f !== 0.0) {
    writer.writeEnum(
      7,
      f
    );
  }
  f = message.getSource();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getDestination();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getDocSource();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
};


/**
 * optional int32 sequence_number = 1;
 * @return {number}
 */
proto.ConversationStreamMessage.prototype.getSequenceNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.ConversationStreamMessage} returns this
 */
proto.ConversationStreamMessage.prototype.setSequenceNumber = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional google.protobuf.Any content = 2;
 * @return {?proto.google.protobuf.Any}
 */
proto.ConversationStreamMessage.prototype.getContent = function() {
  return /** @type{?proto.google.protobuf.Any} */ (
    jspb.Message.getWrapperField(this, google_protobuf_any_pb.Any, 2));
};


/**
 * @param {?proto.google.protobuf.Any|undefined} value
 * @return {!proto.ConversationStreamMessage} returns this
*/
proto.ConversationStreamMessage.prototype.setContent = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ConversationStreamMessage} returns this
 */
proto.ConversationStreamMessage.prototype.clearContent = function() {
  return this.setContent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ConversationStreamMessage.prototype.hasContent = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string date_time = 3;
 * @return {string}
 */
proto.ConversationStreamMessage.prototype.getDateTime = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.ConversationStreamMessage} returns this
 */
proto.ConversationStreamMessage.prototype.setDateTime = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string session_id = 4;
 * @return {string}
 */
proto.ConversationStreamMessage.prototype.getSessionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.ConversationStreamMessage} returns this
 */
proto.ConversationStreamMessage.prototype.setSessionId = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string subscriber_id = 5;
 * @return {string}
 */
proto.ConversationStreamMessage.prototype.getSubscriberId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.ConversationStreamMessage} returns this
 */
proto.ConversationStreamMessage.prototype.setSubscriberId = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string application_name = 6;
 * @return {string}
 */
proto.ConversationStreamMessage.prototype.getApplicationName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.ConversationStreamMessage} returns this
 */
proto.ConversationStreamMessage.prototype.setApplicationName = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional ComponentType message_type = 7;
 * @return {!proto.ComponentType}
 */
proto.ConversationStreamMessage.prototype.getMessageType = function() {
  return /** @type {!proto.ComponentType} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {!proto.ComponentType} value
 * @return {!proto.ConversationStreamMessage} returns this
 */
proto.ConversationStreamMessage.prototype.setMessageType = function(value) {
  return jspb.Message.setProto3EnumField(this, 7, value);
};


/**
 * optional string source = 8;
 * @return {string}
 */
proto.ConversationStreamMessage.prototype.getSource = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.ConversationStreamMessage} returns this
 */
proto.ConversationStreamMessage.prototype.setSource = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string destination = 9;
 * @return {string}
 */
proto.ConversationStreamMessage.prototype.getDestination = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.ConversationStreamMessage} returns this
 */
proto.ConversationStreamMessage.prototype.setDestination = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string doc_source = 10;
 * @return {string}
 */
proto.ConversationStreamMessage.prototype.getDocSource = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.ConversationStreamMessage} returns this
 */
proto.ConversationStreamMessage.prototype.setDocSource = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * @enum {number}
 */
proto.ComponentType = {
  COMPONENT: 0,
  LLM_AGENT: 1,
  API: 2
};

goog.object.extend(exports, proto);
