// automatically generated by the FlatBuffers compiler, do not modify

package MyGame.Sample;

@SuppressWarnings("unused")
public final class ComponentType {
  private ComponentType() { }
  public static final byte COMPONENT = 0;
  public static final byte LLM_AGENT = 1;
  public static final byte API = 2;

  public static final String[] names = { "COMPONENT", "LLM_AGENT", "API", };

  public static String name(int e) { return names[e]; }
}

