// automatically generated by the FlatBuffers compiler, do not modify

package MyGame.Sample;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ConversationStreamMessage extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static ConversationStreamMessage getRootAsConversationStreamMessage(ByteBuffer _bb) { return getRootAsConversationStreamMessage(_bb, new ConversationStreamMessage()); }
  public static ConversationStreamMessage getRootAsConversationStreamMessage(ByteBuffer _bb, ConversationStreamMessage obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ConversationStreamMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int sequenceNumber() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int content(int j) { int o = __offset(6); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int contentLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector contentVector() { return contentVector(new ByteVector()); }
  public ByteVector contentVector(ByteVector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer contentAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer contentInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String dateTime() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer dateTimeAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer dateTimeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String sessionId() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer sessionIdAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer sessionIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public String subscriberId() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer subscriberIdAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer subscriberIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }
  public String applicationName() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer applicationNameAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public ByteBuffer applicationNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 14, 1); }
  public byte messageType() { int o = __offset(16); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public String source() { int o = __offset(18); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer sourceAsByteBuffer() { return __vector_as_bytebuffer(18, 1); }
  public ByteBuffer sourceInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 18, 1); }
  public String destination() { int o = __offset(20); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer destinationAsByteBuffer() { return __vector_as_bytebuffer(20, 1); }
  public ByteBuffer destinationInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 20, 1); }
  public String docSource() { int o = __offset(22); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer docSourceAsByteBuffer() { return __vector_as_bytebuffer(22, 1); }
  public ByteBuffer docSourceInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 22, 1); }

  public static int createConversationStreamMessage(FlatBufferBuilder builder,
      int sequenceNumber,
      int contentOffset,
      int dateTimeOffset,
      int sessionIdOffset,
      int subscriberIdOffset,
      int applicationNameOffset,
      byte messageType,
      int sourceOffset,
      int destinationOffset,
      int docSourceOffset) {
    builder.startTable(10);
    ConversationStreamMessage.addDocSource(builder, docSourceOffset);
    ConversationStreamMessage.addDestination(builder, destinationOffset);
    ConversationStreamMessage.addSource(builder, sourceOffset);
    ConversationStreamMessage.addApplicationName(builder, applicationNameOffset);
    ConversationStreamMessage.addSubscriberId(builder, subscriberIdOffset);
    ConversationStreamMessage.addSessionId(builder, sessionIdOffset);
    ConversationStreamMessage.addDateTime(builder, dateTimeOffset);
    ConversationStreamMessage.addContent(builder, contentOffset);
    ConversationStreamMessage.addSequenceNumber(builder, sequenceNumber);
    ConversationStreamMessage.addMessageType(builder, messageType);
    return ConversationStreamMessage.endConversationStreamMessage(builder);
  }

  public static void startConversationStreamMessage(FlatBufferBuilder builder) { builder.startTable(10); }
  public static void addSequenceNumber(FlatBufferBuilder builder, int sequenceNumber) { builder.addInt(0, sequenceNumber, 0); }
  public static void addContent(FlatBufferBuilder builder, int contentOffset) { builder.addOffset(1, contentOffset, 0); }
  public static int createContentVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createContentVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startContentVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static void addDateTime(FlatBufferBuilder builder, int dateTimeOffset) { builder.addOffset(2, dateTimeOffset, 0); }
  public static void addSessionId(FlatBufferBuilder builder, int sessionIdOffset) { builder.addOffset(3, sessionIdOffset, 0); }
  public static void addSubscriberId(FlatBufferBuilder builder, int subscriberIdOffset) { builder.addOffset(4, subscriberIdOffset, 0); }
  public static void addApplicationName(FlatBufferBuilder builder, int applicationNameOffset) { builder.addOffset(5, applicationNameOffset, 0); }
  public static void addMessageType(FlatBufferBuilder builder, byte messageType) { builder.addByte(6, messageType, 0); }
  public static void addSource(FlatBufferBuilder builder, int sourceOffset) { builder.addOffset(7, sourceOffset, 0); }
  public static void addDestination(FlatBufferBuilder builder, int destinationOffset) { builder.addOffset(8, destinationOffset, 0); }
  public static void addDocSource(FlatBufferBuilder builder, int docSourceOffset) { builder.addOffset(9, docSourceOffset, 0); }
  public static int endConversationStreamMessage(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishConversationStreamMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedConversationStreamMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ConversationStreamMessage get(int j) { return get(new ConversationStreamMessage(), j); }
    public ConversationStreamMessage get(ConversationStreamMessage obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

