// automatically generated by the FlatBuffers compiler, do not modify

package MyGame.Sample;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ConversationItem extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static ConversationItem getRootAsConversationItem(ByteBuffer _bb) { return getRootAsConversationItem(_bb, new ConversationItem()); }
  public static ConversationItem getRootAsConversationItem(ByteBuffer _bb, ConversationItem obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ConversationItem __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String role() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer roleAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer roleInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String content() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer contentAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer contentInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createConversationItem(FlatBufferBuilder builder,
      int roleOffset,
      int contentOffset) {
    builder.startTable(2);
    ConversationItem.addContent(builder, contentOffset);
    ConversationItem.addRole(builder, roleOffset);
    return ConversationItem.endConversationItem(builder);
  }

  public static void startConversationItem(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addRole(FlatBufferBuilder builder, int roleOffset) { builder.addOffset(0, roleOffset, 0); }
  public static void addContent(FlatBufferBuilder builder, int contentOffset) { builder.addOffset(1, contentOffset, 0); }
  public static int endConversationItem(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ConversationItem get(int j) { return get(new ConversationItem(), j); }
    public ConversationItem get(ConversationItem obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

