// automatically generated by the FlatBuffers compiler, do not modify

package MyGame.Sample;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class MemoryModel extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static MemoryModel getRootAsMemoryModel(ByteBuffer _bb) { return getRootAsMemoryModel(_bb, new MemoryModel()); }
  public static MemoryModel getRootAsMemoryModel(ByteBuffer _bb, MemoryModel obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public MemoryModel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public MyGame.Sample.MemoryField memoryFields(int j) { return memoryFields(new MyGame.Sample.MemoryField(), j); }
  public MyGame.Sample.MemoryField memoryFields(MyGame.Sample.MemoryField obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int memoryFieldsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public MyGame.Sample.MemoryField.Vector memoryFieldsVector() { return memoryFieldsVector(new MyGame.Sample.MemoryField.Vector()); }
  public MyGame.Sample.MemoryField.Vector memoryFieldsVector(MyGame.Sample.MemoryField.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createMemoryModel(FlatBufferBuilder builder,
      int memoryFieldsOffset) {
    builder.startTable(1);
    MemoryModel.addMemoryFields(builder, memoryFieldsOffset);
    return MemoryModel.endMemoryModel(builder);
  }

  public static void startMemoryModel(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addMemoryFields(FlatBufferBuilder builder, int memoryFieldsOffset) { builder.addOffset(0, memoryFieldsOffset, 0); }
  public static int createMemoryFieldsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startMemoryFieldsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endMemoryModel(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public MemoryModel get(int j) { return get(new MemoryModel(), j); }
    public MemoryModel get(MemoryModel obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

